ASP.NET WhatWasRead/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASP.NET_WhatWasRead;
using ASP.NET_WhatWasRead.Models;
using Domain.Abstract;
using Domain.Concrete.EF;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Collections.Specialized;
using System.Data.SqlClient;
using System.Configuration;
using System.Text;
using Domain.Infrastructure;
using ASP.NET_WhatWasRead.Infrastructure;

namespace ASP.NET_WhatWasRead.Controllers
{
   public interface IBooksRequestManager
   {
      NameValueCollection GetQueryString(Controller controller);
      NameValueCollection GetQueryStringWhenAppend(Controller controller);
      bool IsAjaxRequest(Controller controller);
   }
   internal sealed class BooksRequestManager : IBooksRequestManager
   {
      public NameValueCollection GetQueryString(Controller controller)
      {
         return controller.Request.QueryString;
      }

      public NameValueCollection GetQueryStringWhenAppend(Controller controller)
      {
         string querystring = controller.Request.UrlReferrer.Query;
         return HttpUtility.ParseQueryString(querystring);
      }

      public bool IsAjaxRequest(Controller controller)
      {
         return controller.Request.IsAjaxRequest();
      }
   }

   public class BooksController : Controller
   {
      private readonly int _booksPerPage = Globals.ITEMS_PER_PAGE;
      private readonly IRepository _repository;
      private IBooksRequestManager _booksRequestManager;

      public BooksController(IRepository repo)
      {
         _repository = repo;
      }
      public IBooksRequestManager BooksRequestManager
      {
         get
         {
            if (_booksRequestManager == null)
            {
               _booksRequestManager = new BooksRequestManager();
            }
            return _booksRequestManager;
         }
         set
         {
            _booksRequestManager = value;
         }
      }

      [HttpGet]
      public ActionResult List(int page = 1, string category = null, string tag = null)
      {
         Category currentCategory = null;
         Tag currentTag = null;
         if (category != null)
         {
            currentCategory = _repository.Categories.Where(cat => cat.NameForLinks == category).FirstOrDefault();
            if (currentCategory == null) //category does not exist
            {
               return View("_NotFoundView");
            }
         }
         if (tag != null)
         {
            currentTag = _repository.Tags.Where(x => x.NameForLinks == tag).FirstOrDefault();
            if (currentTag == null) //tag does not exist
            {
               return View("_NotFoundView");
            }
         }

         //update repository in accordance to query string
         IBooksRequestManager requestManager = this.BooksRequestManager;
         NameValueCollection query = requestManager.GetQueryString(this);
         string[] queryKeys = query.AllKeys;

         if (queryKeys.Length > 0 && !(queryKeys.Length == 1 && (queryKeys[0] == "tag" || queryKeys[0] == "page" || queryKeys[0] == "category")))
         {
            _repository.UpdateBooksFromFilterUsingRawSql(query, "books", "list");
            var pages = query["pages"];
            if (pages != null)
            {
               string[] ar = pages.Split('-');
               if (Int32.TryParse(ar[0], out int min))
               {
                  ViewBag.MinPagesActual = min;
               }
               if (Int32.TryParse(ar[1], out int max))
               {
                  ViewBag.MaxPagesActual = max;
               }
            }
         }

         BooksListViewModel viewModel = new BooksListViewModel();
         if (currentCategory == null) //all categories
         {
            if (currentTag == null) //all categories & all tags
            {
               viewModel.Books = _repository.Books
                   .OrderByDescending(b => b.BookId)
                   .Skip((page - 1) * _booksPerPage)
                   .Take(_booksPerPage).ToList();
               viewModel.PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = _booksPerPage, TotalItems = _repository.Books.Count() };
               viewModel.CurrentCategory = null;
               viewModel.CurrentTag = null;
            }
            else //all categories & specific tag
            {
               viewModel.Books = _repository.Books.Where(b => b.Tags.Select(x => x.TagId).Contains(currentTag.TagId))
                   .OrderByDescending(b => b.BookId)
                   .Skip((page - 1) * _booksPerPage)
                   .Take(_booksPerPage).ToList();
               viewModel.PagingInfo = new PagingInfo { CurrentPage = page, ItemsPerPage = _booksPerPage, TotalItems = _repository.Books.Where(b => b.Tags.Select(x => x.TagId).Contains(currentTag.TagId)).Count() };
               viewModel.CurrentCategory = null;
               viewModel.CurrentTag = currentTag.NameForLinks;
            }
         }
         else //specific category & all tags
         {
            viewModel.Books = _repository.Books
                .Where(b => b.CategoryId == currentCategory.CategoryId)
                .OrderByDescending(b => b.BookId)
                .Skip((page - 1) * _booksPerPage)
                .Take(_booksPerPage).ToList();
            viewModel.PagingInfo = new PagingInfo
            {
               CurrentPage = page,
               ItemsPerPage = _booksPerPage,
               TotalItems = _repository.Books.Where(b => b.CategoryId == currentCategory.CategoryId).Count()
            };
            viewModel.CurrentCategory = currentCategory.NameForLinks;
            viewModel.CurrentTag = null;
         }
         if (requestManager.IsAjaxRequest(this))
         {
            return PartialView("_ListContentView", viewModel);
         }
         return View(viewModel);
      }

      [HttpGet]
      public ActionResult ListToAppend(int page, string category = null, string tag = null)
      {
         Category currentCategory = null;
         Tag currentTag = null;
         if (category != null)
         {
            currentCategory = _repository.Categories.Where(cat => cat.NameForLinks == category).FirstOrDefault();
            if (currentCategory == null) //category does not exist
            {
               return new EmptyResult();
            }
         }
         if (tag != null)
         {
            currentTag = _repository.Tags.Where(x => x.NameForLinks == tag).FirstOrDefault();
            if (currentTag == null) //tag does not exist
            {
               return new EmptyResult();
            }
         }

         IBooksRequestManager requestManager = this.BooksRequestManager;
         NameValueCollection query = requestManager.GetQueryStringWhenAppend(this);
         string[] queryKeys = query.AllKeys;

         if (queryKeys.Length > 0 && !(queryKeys.Length == 1 && (queryKeys[0] == "tag" || queryKeys[0] == "page" || queryKeys[0] == "category")))
         {
            _repository.UpdateBooksFromFilterUsingRawSql(query, "books", "list");
         }

         IEnumerable<Book> books = null;
         if (currentCategory == null) //all categories
         {
            if (currentTag == null) //all categories & all tags
            {
               books = _repository.Books
                   .OrderByDescending(b => b.BookId)
                   .Skip((page - 1) * _booksPerPage)
                   .Take(_booksPerPage).ToList();
            }
            else //all categories & specific tag
            {
               books = _repository.Books.Where(b => b.Tags.Select(x => x.TagId).Contains(currentTag.TagId))
                   .OrderByDescending(b => b.BookId)
                   .Skip((page - 1) * _booksPerPage)
                   .Take(_booksPerPage).ToList();
            }
         }
         else //specific category
         {
               books = _repository.Books
                   .Where(b => b.CategoryId == currentCategory.CategoryId)
                   .OrderByDescending(b => b.BookId)
                   .Skip((page - 1) * _booksPerPage)
                   .Take(_booksPerPage);
         }

         if (books == null || books.Count() == 0)
         {
            return new EmptyResult();
         }
         return PartialView("_BookRowsPartialView", books);
      }

      public FileContentResult GetImage(int id)
      {
         Book book = _repository.Books.FirstOrDefault(p => p.BookId == id);
         if (book != null)
         {
            return File(book.ImageData, book.ImageMimeType);
         }
         else
         {
            return null;
         }
      }

      [HttpGet]
      public ActionResult Details(int id)
      {
         Book book = _repository.FindBook(id);
         if (book == null)
         {
            return HttpNotFound();
         }
         return View(book);
      }
      // GET: Books/Create
      public ActionResult Create()
      {
         CreateEditBookViewModel model = new Models.CreateEditBookViewModel();
         ViewBag.CategoryId = new SelectList(_repository.Categories, "CategoryId", "NameForLabels");
         ViewBag.LanguageId = new SelectList(_repository.Languages, "LanguageId", "NameForLabels");
         model.Authors = _repository.Authors.OrderBy(x => x.LastName).Select(x => new SelectListItem { Value = x.AuthorId.ToString(), Text = x.LastName + " " + x.FirstName }).ToList();
         model.Tags = _repository.Tags.OrderBy(x => x.NameForLabels).Select(x => new SelectListItem { Value = x.TagId.ToString(), Text = x.NameForLabels }).ToList();
         return View(model);
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "BookId,Name,LanguageId,Pages,Description,CategoryId,Year,SelectedAuthors,ImageData,ImageMimeType,SelectedTags")] CreateEditBookViewModel model, HttpPostedFileBase image)
      {

ASP.NET WhatWasRead/Controllers/NavigationController.cs
using ASP.NET_WhatWasRead.Models;
using Domain.Abstract;
using Domain.Concrete;
using Domain.Concrete.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP.NET_WhatWasRead.Controllers
{
   public class NavigationController : Controller
   {
      private IRepository repository;
      public NavigationController(IRepository repository)
      {
         this.repository = repository;
      }

      [ChildActionOnly]
      public PartialViewResult ListOfCategories(string currentCategory, string currentTag, int? minPages, int? maxPages)
      {
         NavigationViewModel model = new NavigationViewModel();
         IEnumerable<Category> categories = repository.Categories.OrderBy(c => c.NameForLabels).ToList();
         IEnumerable<Tag> tags = repository.Tags.OrderBy(t => t.NameForLabels).ToList();
         IEnumerable<Author> authors = repository.Authors.OrderBy(f => f.LastName).ToList();
         IEnumerable<Language> languages = repository.Languages.OrderBy(f => f.NameForLabels).ToList();
         int minPagesDB = repository.Books.Count() > 0 ? repository.Books.Select(b => b.Pages).Min() : 0;
         int maxPagesDB = repository.Books.Count() > 0 ? repository.Books.Select(b => b.Pages).Max() : 0;

         model.Categories = categories;
         model.Tags = tags;
         model.Authors = authors;
         model.Languages = languages;
         model.MinPagesExpected = minPagesDB;
         model.MaxPagesExpected = maxPagesDB;
         model.CurrentCategory = currentCategory;
         model.CurrentTag = currentTag;
         model.MinPagesActual = minPages.HasValue ? Math.Max(minPages.Value, minPagesDB) : minPagesDB;
         model.MaxPagesActual = maxPages.HasValue ? Math.Min(maxPages.Value, maxPagesDB) : maxPagesDB;
         return PartialView("ListOfCategories", model);
      }
   }
}

ASP.NET WhatWasRead/Views/Books/BookDetails.cshtml
@model Domain.Concrete.EF.Book

@{
    ViewBag.Title = "Книги: подробно";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BookDetails</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.NameForLabels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.NameForLabels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language.NameForLabels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.NameForLabels)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "Books", new { id = Model.BookId }, null) |
    @Html.ActionLink("Back to List", "List")
</p>

ASP.NET WhatWasRead/Views/Books/Create.cshtml
@model  CreateEditBookViewModel

@{
    ViewBag.Title = "Книги: добавление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-left: 10px">Добавить прочтенную книгу</h2>
<hr />
@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_CreateEditBook", Model)
}

ASP.NET WhatWasRead/Views/Books/Delete.cshtml
@model Domain.Concrete.EF.Book

@{
    ViewBag.Title = "Книги: удаление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-left: 10px">Удаление</h2>

<h3 style="margin-left: 10px">Вы точно хотите удалить данные о книге?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Name, "Название:")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Authors, Model.Authors.Count > 1 ? "Авторы:" : "Автор:")
        </dt>
        <dd>
            @Model.DisplayAuthors()
        </dd>

        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Pages, "Количество страниц:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pages)
        </dd>

        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Description, "Описание:")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Year, "Год издания:")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Category.NameForLabels, "Категория:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.NameForLabels)
        </dd>

        <dt class="dt-label" style="text-align: left">
            @Html.LabelFor(model => model.Language.NameForLabels, "Язык:")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.NameForLabels)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color col-md-offset-2" >
            <input type="submit" value="Удалить" class="btn btn-warning" />
        </div>
    }
</div>

ASP.NET WhatWasRead/Views/Books/Details.cshtml
@using System.Text
@using Domain.Concrete.EF;
@using ASP.NET_WhatWasRead.HtmlHelpers;

@model Book
@{
    ViewBag.Title = "Книги: подробно";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-left: 10px">Подробнее</h2>

<div>
    <hr />
    <div class="details-left-side-panel">
        <div class="form-group">
            @if (Model.ImageData == null)
            {
                <div class="form-control-static">No Image</div>
            }
            else
            {
                <img class="img-thumbnail" width="152" height="215" src="@Url.RouteUrl("BooksIdAction", new { controller = "Books", action = "GetImage", id = Model.BookId })" />
            }
        </div>
    </div>
    <div class="details-rigth-side-panel">
        <dl class="dl-horizontal">
            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Name, "Название:")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Authors, Model.Authors.Count > 1 ? "Авторы:" : "Автор:")
            </dt>
            <dd>
                @Model.DisplayAuthors()
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Pages, "Количество страниц:")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Pages)
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Description, "Описание:")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Year, "Год издания:")
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Year)
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Category.NameForLabels, "Категория:")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category.NameForLabels)
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Language.NameForLabels, "Язык:")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Language.NameForLabels)
            </dd>

            <dt class="dt-label" style="text-align: left">
                @Html.LabelFor(model => model.Tags, "Теги:")
            </dt>

            <dd>
                @Html.CreateTagLinks(Model.Tags.ToArray())
            </dd>

        </dl>
    </div>
</div>

<p style="margin-left: 10px; font-size:medium">
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.BookId }) |
    @Html.ActionLink("Удалить", "Delete", new { id = Model.BookId })
</p>

ASP.NET WhatWasRead/Views/Books/Edit.cshtml
@model CreateEditBookViewModel

@{
    ViewBag.Title = "Книги: редактирование";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<h2 style="margin-left: 10px">Редактирование информации о книге</h2>

@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_CreateEditBook", Model)
}

ASP.NET WhatWasRead/Views/Books/List.cshtml
@model BooksListViewModel

@{
    ViewBag.Title = "Книги: список";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Html.Partial("_ListContentView", Model)

ASP.NET WhatWasRead/Views/Books/_BookRowsPartialView.cshtml
@using Domain.Concrete.EF;
@using ASP.NET_WhatWasRead.Infrastructure;

@model IEnumerable<Book>

@{IEnumerator<Book> enumerator = Model.GetEnumerator(); }
@while(enumerator.MoveNext())
{
    int booksInRowCount = 0;
    Book currentBook = enumerator.Current;
    <div class="row-books">
        @while (true)
        {
            @ImgAndAbout(currentBook);
            booksInRowCount++;
            if (booksInRowCount % Globals.ITEMS_PER_BOOKROW == 0)
            {
                break; //start new booksRow
            }
            else
            {
                if (enumerator.MoveNext()) // go to next element
                {
                    currentBook = enumerator.Current;
                }
                else
                {
                    break;
                }
            }
        }
    </div>
}

@helper ImgAndAbout(Book book)
{
    <div class="img-and-about">
        <div class="book-img">
            <img src="@(book.ImageData == null ? @"\Images\no_image.png" : Url.Action("GetImage", "Books", new { id = book.BookId }) )" alt="@book.Name" />
        </div>
        <div class="book-name">
            <p>@book.Name</p>
        </div>
        <div class="book-authors">
            <p>@((book.Authors.Count == 1 ? "Автор: " : "Авторы: ") + @book.DisplayAuthors())</p>
        </div>
        <div class="book-details">
            <a href="@Url.RouteUrl("BooksIdAction", new { id = book.BookId, action = "Details" })">Подробнее</a>
        </div>
    </div>
}

ASP.NET WhatWasRead/Views/Books/_CreateEditBook.cshtml
@model CreateEditBookViewModel

<div class="details-left-side-panel">
    <div class="form-group">
       @Html.ValidationMessageFor(model=>model.ImageData)
        <div style="position:relative;">
            <a class='btn' href='javascript:;'>
                Выбрать обложку...
                <input type="file" name="Image" accept=".jpg, .jpeg, .png" style="position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0); opacity:0;background-color:transparent;color:transparent;"
                       onchange="readURL(this);" />
            </a>
            <span class='label label-info' id="upload-file-info"></span>
        </div>
        <div>
            @{
                if (Model.ImageData != null)
                {
                    string base64 = Convert.ToBase64String(Model.ImageData);
                    string imgSrc = String.Format("data:image/jpg;base64,{0}", base64);
                    <img class="img-thumbnail" id="img-thumbnail" name="ImageData" width="152" height="215" alt="No image" src="@imgSrc" />
                        <span>
                            @Html.HiddenFor(x => x.ImageData)
                            @Html.HiddenFor(x => x.ImageMimeType)
                        </span>
                }
                else
                {
                    <img class="img-thumbnail" id="img-thumbnail" name="ImageData" width="152" height="215" alt="No image"/>
                }
            }
        </div>
    </div>
</div>

<div class="details-rigth-side-panel">
    <div class="form-horizontal" style="height:auto">
        @Html.HiddenFor(model => model.BookId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Название:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "Введите название", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Authors, "Авторы:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-2">
                @Html.ListBoxFor(x => x.SelectedAuthors, Model.Authors, new { @class = "form-control", size = 10 })
                @Html.ValidationMessageFor(model => model.SelectedAuthors, "Выберите хотя бы одного автора", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pages, "Количество страниц:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-1">
                @Html.EditorFor(model => model.Pages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pages, "Укажите количество страниц", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, "Год издания:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-1">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "Укажите корректный год издания", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Описание:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", style = "height:150px" } })
                @Html.ValidationMessageFor(model => model.Description, "Введите описание", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanguageId, "Язык:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-2">
                @Html.DropDownList("LanguageId", (IEnumerable<SelectListItem>)ViewBag.Languages, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LanguageId, "Выберите язык", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Категория:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-2">
                @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.Categories, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "Выберите категорию", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, "Teги:", htmlAttributes: new { @class = "book-details-label" })
            <div class="col-md-2">
                @Html.ListBoxFor(x => x.SelectedTags, Model.Tags, new { @class = "form-control", size = 10 })
            </div>
        </div>

    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
</div>
                    }

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#img-thumbnail')
                    .attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

ASP.NET WhatWasRead/Views/Books/_ListContentView.cshtml
@using System.Text;
@using ASP.NET_WhatWasRead.HtmlHelpers
@model BooksListViewModel

<div id="center">
    @Html.Action("ListOfCategories", "Navigation", new { currentCategory = Model.CurrentCategory, currentTag = Model.CurrentTag, minPages = ViewBag.MinPagesActual, maxPages = ViewBag.MaxPagesActual }) @*//слева список категорий*@
    <div id="right-panel">
        <div id="books-list-wrapper">
            @if (Model.Books.Count()>0)
            {
                @Html.Partial("_BookRowsPartialView", Model.Books)
            }
            else
            {
                @Html.Partial("_NoResultPartialView")
            }
        </div>

        <div class="bottom-paging-wrapper">
            <div class="bottom-paging">
                @if (Model.CurrentCategory == null)
                {
                   for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
                   {
                      string url = Url.RouteUrl("PageRoute", new { controller = "Books", action = "List", page = i, tag = Model.CurrentTag });
                      if (Request.QueryString.Count != 0 && !(Request.QueryString.Count == 1 && (Request.QueryString.AllKeys[0] == "tag" || Request.QueryString.AllKeys[0] == "page") || Request.QueryString.AllKeys[0] == "category"))
                      {
                         //bool b;
                         //url = Html.CreateFilterPartOfLink(Request.Path, Request.QueryString, "page", i.ToString(), out b);
                         url += Helper.BuildQueryString(Request.QueryString);
                      }
                        <a href="@url" class="@(i == Model.PagingInfo.CurrentPage ? "page-link selected" : "page-link")">@i.ToString()</a>
                   }
                }
                else
                {
                   for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
                   {
                      string url = Url.RouteUrl("CategoryPageRoute", new { controller = "Books", action = "List", page = i, category = Model.CurrentCategory, tag = Model.CurrentTag });
                      if (Request.QueryString.Count != 0 && !(Request.QueryString.Count == 1 && (Request.QueryString.AllKeys[0] == "tag" || Request.QueryString.AllKeys[0] == "page") || Request.QueryString.AllKeys[0] == "category"))
                      {
                         url += Helper.BuildQueryString(Request.QueryString);
                      }

                        <a href="@url" class="@(i == Model.PagingInfo.CurrentPage ? "page-link selected" : "page-link")">@i.ToString()</a>
                    }
                }
            </div>
            <div class="btn-placeholder">
                <button id="btn-load-more" class="btn btn-success" type="button" @(Model.PagingInfo.TotalPages == 0 || Model.PagingInfo.TotalPages == Model.PagingInfo.CurrentPage ? "disabled" : "")>Показать еще</button>
            </div>
        </div>
    </div>
</div>

ASP.NET WhatWasRead/Views/Books/_NoResultPartialView.cshtml
<h3>Ничего не найдено. Измените критерии выбора</h3> 